export type ShadowTooltipPosition = 'top' | 'bottom' | 'left' | 'right'
export type ShadowTooltipTheme = 'dark' | 'light'
export type ShadowTooltipCaretAlignment = 'start' | 'center' | 'end'
export type ShadowTooltipEvent = 'hover' | 'click'
export type ShadowTooltipType = 'single' | 'multiple'
